import { useAppStore } from '../store/appStore'

export type UiLanguage = 'ar' | 'en'

const strings = {
  ar: {
    home: 'الرئيسية', create: 'إنشاء لعبة', about: 'عن المطور', board: 'لوحة اللعب', question: 'السؤال', results: 'النتائج', settings: 'الإعدادات', admin: 'الإدارة',
    welcome: 'مرحبًا بك في', arena: 'فهلوي', subtitle: 'منصة مسابقات احترافية تجمع الأصدقاء في تحدٍ واحد.', newGame: 'لعبة جديدة', viewBoard: 'فتح لوحة اللعب', categories: 'فئات متنوعة', categoriesDesc: 'مواضيع مصممة لجولات ممتعة ومتوازنة', teams: 'فرق تنافسية', teamsDesc: 'نظام نقاط حي وتحديات جماعية', rtl: 'واجهة عربية كاملة', rtlDesc: 'تجربة مصممة للغة العربية والإنجليزية',
    createTitle: 'إنشاء لعبة جديدة', createDesc: 'اختر الفئات، جهّز الفرق، وابدأ الجولة.', teamSetup: 'إعداد الفرق', stepsTeams: 'الفرق', stepsCategories: 'الفئات', stepsSettings: 'إعدادات اللعبة', stepsReview: 'مراجعة', next: 'التالي', selectionSummary: 'ملخص الاختيار', categoryCount: 'فئات', questionCount: 'سؤال', selectionHint: 'اختر 3 فئات لكل فريق. سيتم اختيار الأسئلة بشكل عشوائي من الفئات المختارة.', availableCategory: 'فئة متاحة', selectedCategory: 'فئة مختارة', chooseCategories: 'اختيار الفئات', searchCategories: 'ابحث عن فئة...', noCategories: 'لا توجد فئات مطابقة.', teamOne: 'الفريق الأول', teamTwo: 'الفريق الثاني', chooseFor: 'يختار ٣ فئات', selectionProgress: 'تقدم اختيار الفئات', turn: 'دور الاختيار', complete: 'مكتمل', selected: 'المختار', startGame: 'ابدأ اللعبة', chooseRequirements: 'اختر ٣ فئات و٣ مساعدات لكل فريق للبدء', gameName: 'اسم اللعبة', teamOneName: 'اسم الفريق الأول', teamTwoName: 'اسم الفريق الثاني', playersOne: 'عدد لاعبي الفريق الأول', playersTwo: 'عدد لاعبي الفريق الثاني', decrease: 'تقليل', increase: 'زيادة', lifelines: 'مساعدات',
    settingsTitle: 'الإعدادات', language: 'لغة الواجهة', arabic: 'العربية', english: 'English', sound: 'المؤثرات الصوتية', music: 'الموسيقى الخلفية', gameplay: 'إعدادات اللعب', appearance: 'المظهر', reset: 'إعادة الإعدادات', cancel: 'إلغاء', confirm: 'تأكيد',
  },
  en: {
    home: 'Home', create: 'Create Game', about: 'About', board: 'Game Board', question: 'Question', results: 'Results', settings: 'Settings', admin: 'Admin',
    welcome: 'Welcome to', arena: 'Fahloy', subtitle: 'A professional quiz experience that brings teams together for one exciting challenge.', newGame: 'New game', viewBoard: 'Open game board', categories: 'Curated categories', categoriesDesc: 'Topics designed for balanced, engaging rounds', teams: 'Competitive teams', teamsDesc: 'Live scoring and team-based challenges', rtl: 'Bilingual experience', rtlDesc: 'A polished interface in Arabic and English',
    createTitle: 'Create a new game', createDesc: 'Choose categories, prepare your teams, and start the round.', teamSetup: 'Team setup', stepsTeams: 'Teams', stepsCategories: 'Categories', stepsSettings: 'Game settings', stepsReview: 'Review', next: 'Next', selectionSummary: 'Selection summary', categoryCount: 'categories', questionCount: 'questions', selectionHint: 'Choose 3 categories for each team. Questions will be selected randomly from your choices.', availableCategory: 'Available category', selectedCategory: 'Selected category', chooseCategories: 'Choose categories', searchCategories: 'Search categories...', noCategories: 'No matching categories.', teamOne: 'Team one', teamTwo: 'Team two', chooseFor: 'chooses 3 categories', selectionProgress: 'Selection progress', turn: 'Selection turn', complete: 'Complete', selected: 'Selected', startGame: 'Start game', chooseRequirements: 'Choose 3 categories and 3 lifelines for each team', gameName: 'Game name', teamOneName: 'Team one name', teamTwoName: 'Team two name', playersOne: 'Players — team one', playersTwo: 'Players — team two', decrease: 'Decrease', increase: 'Increase', lifelines: 'Lifelines',
    settingsTitle: 'Settings', language: 'Interface language', arabic: 'العربية', english: 'English', sound: 'Sound effects', music: 'Background music', gameplay: 'Gameplay', appearance: 'Appearance', reset: 'Reset settings', cancel: 'Cancel', confirm: 'Confirm',
  },
} as const

export function useTranslation() {
  const language = useAppStore((state) => state.language)
  return { language, english: language === 'en', t: (key: keyof typeof strings.ar) => strings[language][key] }
}

const categoryEnglish: Record<string, string> = {
  'general-knowledge': 'General Knowledge', science: 'Science', technology: 'Technology', riddles: 'Riddles', intelligence: 'Logic & Intelligence', celebrities: 'Celebrities', cars: 'Cars', companies: 'Companies', currencies: 'Currencies', inventions: 'Inventions', logos: 'Logos', 'who-am-i-general': 'Who am I?', countries: 'Countries', capitals: 'World Capitals', flags: 'Flags', cities: 'Cities', 'tourist-attractions': 'Landmarks', rivers: 'Rivers', mountains: 'Mountains', egypt: 'Egypt', 'arab-world': 'Arab World', 'city-country': 'City & Country', 'currency-country': 'Currencies & Countries', 'egyptian-history': 'Egyptian History', 'pharaonic-civilization': 'Pharaonic Civilization', 'islamic-history': 'Islamic History', 'world-wars': 'World Wars', civilizations: 'Civilizations', 'historical-figures': 'Historical Figures', 'arabic-movies': 'Arabic Movies', 'foreign-movies': 'Foreign Movies', marvel: 'Marvel', dc: 'DC', 'harry-potter': 'Harry Potter', 'fast-furious': 'Fast & Furious', 'egyptian-series': 'Egyptian Series', 'arabic-series': 'Arabic Series', 'turkish-series': 'Turkish Series', 'korean-series': 'Korean Series', netflix: 'Netflix', actors: 'Actors', actresses: 'Actresses', 'who-is-character': 'Who is this character?', 'egyptian-posters': 'Egyptian Posters', football: 'Football', 'world-cup': 'World Cup', 'uefa-champions': 'UEFA Champions League', 'english-premier': 'English Premier League', 'la-liga': 'La Liga', 'serie-a': 'Serie A', bundesliga: 'Bundesliga', 'ligue-1': 'Ligue 1', 'egyptian-league': 'Egyptian League', 'saudi-league': 'Saudi League', 'national-teams': 'National Teams', clubs: 'Clubs', 'club-logos': 'Club Logos', stadiums: 'Stadiums', coaches: 'Coaches', referees: 'Referees', 'player-transfers': 'Transfers', records: 'Records', messi: 'Messi', ronaldo: 'Ronaldo', 'mohamed-salah': 'Mohamed Salah', basketball: 'Basketball', tennis: 'Tennis', 'formula-1': 'Formula 1', wwe: 'WWE', ufc: 'UFC', 'match-result': 'Match Results', 'player-career': 'Player Careers', 'who-am-i-sports': 'Who am I?', 'who-scored': 'Who Scored?', 'world-cup-26': 'World Cup 2026',
}
const sectionEnglish: Record<string, string> = { all: 'All', general: 'General', geography: 'Geography', history: 'History', movies: 'Movies', sports: 'Sports' }
const lifelineEnglish: Record<string, { label: string; description: string }> = {
  double: { label: 'Double points', description: 'Double this question\'s points' }, 'two-answers': { label: 'Four answers', description: 'Reveal up to four available answers' }, block: { label: 'Block opponent', description: 'Prevent the other team from answering' }, call: { label: 'Call a friend', description: 'Ask for help for 30 seconds' }, wheel: { label: 'Lucky wheel', description: 'Spin for a random reward' },
}
export function presentCategory(id: string, arabic: string, english: boolean) { return english ? categoryEnglish[id] ?? id : arabic }
export function presentSection(id: string, arabic: string, english: boolean) { return english ? sectionEnglish[id] ?? id : arabic }
export function presentLifeline(id: string, arabic: string, description: string, english: boolean) { return english ? lifelineEnglish[id] ?? { label: id, description: id } : { label: arabic, description } }
