import { useAppStore } from '../store/appStore'

export type UiLanguage = 'ar' | 'en'

const strings = {
  ar: {
    home: 'الرئيسية', create: 'إنشاء لعبة', about: 'عن المطور', board: 'لوحة اللعب', question: 'السؤال', results: 'النتائج', settings: 'الإعدادات', admin: 'الإدارة',
    welcome: 'مرحبًا بك في', arena: 'فهلوي', subtitle: 'منصة مسابقات احترافية تجمع الأصدقاء في تحدٍ واحد.', newGame: 'لعبة جديدة', viewBoard: 'فتح لوحة اللعب', categories: 'فئات متنوعة', categoriesDesc: 'مواضيع مصممة لجولات ممتعة ومتوازنة', teams: 'فرق تنافسية', teamsDesc: 'نظام نقاط حي وتحديات جماعية', rtl: 'واجهة عربية كاملة', rtlDesc: 'تجربة مصممة للغة العربية والإنجليزية',
    heroBadge: 'مسابقة معرفية أونلاين', heroTag: 'اللعبة اللي هتختبر معلوماتك بجد', heroDesc: 'أسئلة، تحديات، مساعدات ومنافسة أونلاين — مين هيطلع الفهلوي؟', ctaPlay: 'ابدأ اللعب', ctaOnline: 'العب أونلاين', heroReady: 'جاهز تثبت إنك الفهلوي؟', heroReadyDesc: 'افتح اللعبة، اختار فئاتك، وابدأ التحدي.',
    sec1Title: 'اختبر معلوماتك', sec1Desc: 'مئات الأسئلة في كل فئة — من العواصم والرياضة لحد السينما والتاريخ.', sec2Title: 'نافس أصحابك', sec2Desc: 'فرق متكافئة، أدوار متبادلة، ونقاط بتتحسب لحظيًا على لوحة واحدة.', sec3Title: 'استخدم المساعدات', sec3Desc: 'اتصال بصديق، حظر الخصم، مضاعفة النقاط، وعجلة الحظ — كل أداة ليها لحظتها.', sec4Title: 'العب أونلاين', sec4Desc: 'أنشئ غرفة، شارك الكود، ولعبوا مع بعض في الوقت الفعلي — لحد ٦ لاعبين.', sec5Title: 'مين هيكون الفهلوي؟', sec5Desc: 'كل جولة بتتغير، وكل سؤال فرصة تثبت فيها نفسك.', demoQuestion: 'أكبر دولة عربية من حيث المساحة؟', demoAnswer: 'الجزائر', demoReveal: 'كشف الإجابة', demoReady: 'جاهزة للبدء', demoTurn: 'الدور الحالي', demoLive: 'مباشر', demoWaiting: 'بانتظار لاعبين…',
    introLine: 'مين هيكون الفهلوي؟', scrollHint: 'ابدأ الرحلة', sceneTag: 'الفئة', sceneFootball: 'أسئلة تنافسية في كرة القدم', sceneHistory: 'اختبر معلوماتك في التاريخ', sceneGeography: 'اكتشف العالم واختبر معلوماتك', sceneScience: 'أسئلة تختبر ذكاءك', sceneMovies: 'اختبر معلوماتك في الأفلام', sceneGeneral: 'اختبر معلوماتك العامة', sceneComp1: 'نافس أصحابك', sceneComp2: 'اختبر معلوماتك', sceneComp3: 'اكسب', sceneLifelines: 'استخدم المساعدات', sceneOnline: 'العب أونلاين', sceneOnlineDesc: 'نافس أصحابك في الوقت الحقيقي', navHow: 'طريقة اللعب', soundOn: 'تشغيل الصوت', soundOff: 'إيقاف الصوت',
    mosaicTitle: 'عوالم المعرفة', mosaicDesc: 'ست عوالم — كل واحدة عالم مستقل بأسئلته وأجوائه', mosaicFootball: 'كرة القدم', mosaicHistory: 'التاريخ', mosaicGeography: 'الجغرافيا', mosaicScience: 'العلوم', mosaicMovies: 'الأفلام', mosaicGeneral: 'معلومات عامة',
    howTitle: 'طريقة اللعب', howStep1: 'اختار الفئة', howStep1Desc: 'ابدأ من أي عالم تحبه', howStep2: 'اختار النقاط', howStep2Desc: 'كلما زادت، زاد التحدي', howStep3: 'جاوب', howStep3Desc: 'مع الوقت والمساعدات', howStep4: 'اكسب', howStep4Desc: 'اجمع النقاط وكن الفهلوي',
    onlineArenaTitle: 'لعب أونلاين', onlineArenaDesc: 'أنشئ غرفة، شارك الكود، ونافس أصحابك لحظيًا', onlineArenaCta: 'ادخل الساحة', onlineArenaLive: 'مباشر الآن — حتى ٦ لاعبين',
    createTitle: 'إنشاء لعبة جديدة', createDesc: 'اختر الفئات، جهّز الفرق، وابدأ الجولة.', teamSetup: 'إعداد الفرق', stepsTeams: 'الفرق', stepsCategories: 'الفئات', stepsSettings: 'إعدادات اللعبة', stepsReview: 'مراجعة', next: 'التالي', selectionSummary: 'ملخص الاختيار', categoryCount: 'فئات', questionCount: 'سؤال', selectionHint: 'اختر 3 فئات لكل فريق. سيتم اختيار الأسئلة بشكل عشوائي من الفئات المختارة.', availableCategory: 'فئة متاحة', selectedCategory: 'فئة مختارة', chooseCategories: 'اختيار الفئات', searchCategories: 'ابحث عن فئة...', noCategories: 'لا توجد فئات مطابقة.', teamOne: 'الفريق الأول', teamTwo: 'الفريق الثاني', chooseFor: 'يختار ٣ فئات', selectionProgress: 'تقدم اختيار الفئات', turn: 'دور الاختيار', complete: 'مكتمل', selected: 'المختار', startGame: 'ابدأ اللعبة', chooseRequirements: 'اختر ٣ فئات و٣ مساعدات لكل فريق للبدء', gameName: 'اسم اللعبة', teamOneName: 'اسم الفريق الأول', teamTwoName: 'اسم الفريق الثاني', playersOne: 'عدد لاعبي الفريق الأول', playersTwo: 'عدد لاعبي الفريق الثاني', decrease: 'تقليل', increase: 'زيادة', lifelines: 'مساعدات',
    playOnline: 'لعب أونلاين', onlineTitle: 'لعب أونلاين', onlineSubtitle: 'أنشئ غرفة جديدة أو انضم إلى غرفة صديقك', playerName: 'اسم اللاعب', enterName: 'أدخل اسم اللاعب أولًا', createRoom: 'إنشاء غرفة', or: 'أو', roomCode: 'كود اللعبة', joinGame: 'دخول اللعبة', invalidCode: 'كود غير صالح — استخدم ٦ أحرف وأرقام', back: 'رجوع', room: 'غرفة', roomWaiting: 'بانتظار اللاعبين', roomReady: 'جاهزة للبدء', you: 'أنت', waitingForPlayer: 'في انتظار اللاعب...', copyCode: 'نسخ الكود', copied: 'تم النسخ ✓', waitingForOpponent: 'بانتظار اللاعب الثاني لبدء اللعبة', leaveRoom: 'مغادرة الغرفة', onlineLive: 'مباشر عبر الإنترنت', noRoom: 'لا توجد غرفة', noRoomDesc: 'ادخل إلى غرفة من صفحة لعب أونلاين', hostLeft: 'خرج المضيف من الغرفة',
    settingsTitle: 'الإعدادات', language: 'لغة الواجهة', arabic: 'العربية', english: 'English', sound: 'المؤثرات الصوتية', music: 'الموسيقى الخلفية', gameplay: 'إعدادات اللعب', appearance: 'المظهر', reset: 'إعادة الإعدادات', cancel: 'إلغاء', confirm: 'تأكيد',
  },
  en: {
    home: 'Home', create: 'Create Game', about: 'About', board: 'Game Board', question: 'Question', results: 'Results', settings: 'Settings', admin: 'Admin',
    welcome: 'Welcome to', arena: 'Fahloy', subtitle: 'A professional quiz experience that brings teams together for one exciting challenge.', newGame: 'New game', viewBoard: 'Open game board', categories: 'Curated categories', categoriesDesc: 'Topics designed for balanced, engaging rounds', teams: 'Competitive teams', teamsDesc: 'Live scoring and team-based challenges', rtl: 'Bilingual experience', rtlDesc: 'A polished interface in Arabic and English',
    heroBadge: 'Online trivia arena', heroTag: 'The game that truly tests what you know', heroDesc: 'Questions, challenges, lifelines and online competition — who will be the Fahloy?', ctaPlay: 'Start playing', ctaOnline: 'Play online', heroReady: 'Ready to prove you are the Fahloy?', heroReadyDesc: 'Open the game, pick your categories, and start the challenge.',
    sec1Title: 'Test your knowledge', sec1Desc: 'Hundreds of questions across every category — from capitals and sports to movies and history.', sec2Title: 'Compete with your friends', sec2Desc: 'Balanced teams, rotating turns, and live scoring on one shared board.', sec3Title: 'Use your lifelines', sec3Desc: 'Call a friend, block the opponent, double points, and spin the wheel — every tool has its moment.', sec4Title: 'Play online', sec4Desc: 'Create a room, share the code, and play together in real time — up to 6 players.', sec5Title: 'Who will be the Fahloy?', sec5Desc: 'Every round changes, and every question is a chance to prove yourself.', demoQuestion: 'Which is the largest Arab country by area?', demoAnswer: 'Algeria', demoReveal: 'Reveal answer', demoReady: 'Ready to start', demoTurn: 'Current turn', demoLive: 'Live', demoWaiting: 'Waiting for players…',
    introLine: 'Who will be the Fahloy?', scrollHint: 'Start the journey', sceneTag: 'Category', sceneFootball: 'Competitive questions in football', sceneHistory: 'Test your knowledge in history', sceneGeography: 'Discover the world and test your knowledge', sceneScience: 'Questions that test your intelligence', sceneMovies: 'Test your knowledge in movies', sceneGeneral: 'Test your general knowledge', sceneComp1: 'Compete with your friends', sceneComp2: 'Test your knowledge', sceneComp3: 'Win', sceneLifelines: 'Use your lifelines', sceneOnline: 'Play online', sceneOnlineDesc: 'Compete with your friends in real time', navHow: 'How to play', soundOn: 'Enable sound', soundOff: 'Mute sound',
    mosaicTitle: 'Worlds of knowledge', mosaicDesc: 'Six worlds — each an independent universe with its own questions and atmosphere', mosaicFootball: 'Football', mosaicHistory: 'History', mosaicGeography: 'Geography', mosaicScience: 'Science', mosaicMovies: 'Movies', mosaicGeneral: 'General Knowledge',
    howTitle: 'How to play', howStep1: 'Pick a category', howStep1Desc: 'Start from any world you love', howStep2: 'Pick the points', howStep2Desc: 'The higher, the harder', howStep3: 'Answer', howStep3Desc: 'Against the clock, with lifelines', howStep4: 'Win', howStep4Desc: 'Gather points and become the Fahloy',
    onlineArenaTitle: 'Play online', onlineArenaDesc: 'Create a room, share the code, and compete with your friends live', onlineArenaCta: 'Enter the arena', onlineArenaLive: 'Live now — up to 6 players',
    createTitle: 'Create a new game', createDesc: 'Choose categories, prepare your teams, and start the round.', teamSetup: 'Team setup', stepsTeams: 'Teams', stepsCategories: 'Categories', stepsSettings: 'Game settings', stepsReview: 'Review', next: 'Next', selectionSummary: 'Selection summary', categoryCount: 'categories', questionCount: 'questions', selectionHint: 'Choose 3 categories for each team. Questions will be selected randomly from your choices.', availableCategory: 'Available category', selectedCategory: 'Selected category', chooseCategories: 'Choose categories', searchCategories: 'Search categories...', noCategories: 'No matching categories.', teamOne: 'Team one', teamTwo: 'Team two', chooseFor: 'chooses 3 categories', selectionProgress: 'Selection progress', turn: 'Selection turn', complete: 'Complete', selected: 'Selected', startGame: 'Start game', chooseRequirements: 'Choose 3 categories and 3 lifelines for each team', gameName: 'Game name', teamOneName: 'Team one name', teamTwoName: 'Team two name', playersOne: 'Players — team one', playersTwo: 'Players — team two', decrease: 'Decrease', increase: 'Increase', lifelines: 'Lifelines',
    playOnline: 'Play online', onlineTitle: 'Play Online', onlineSubtitle: 'Create a new room or join your friend\'s', playerName: 'Player name', enterName: 'Enter a player name first', createRoom: 'Create room', or: 'or', roomCode: 'Game code', joinGame: 'Join game', invalidCode: 'Invalid code — use 6 letters and digits', back: 'Back', room: 'Room', roomWaiting: 'Waiting for players', roomReady: 'Ready to start', you: 'You', waitingForPlayer: 'Waiting for player...', copyCode: 'Copy code', copied: 'Copied ✓', waitingForOpponent: 'Waiting for the second player to start', leaveRoom: 'Leave room', onlineLive: 'Live via internet', noRoom: 'No room', noRoomDesc: 'Enter a room from the Play Online page', hostLeft: 'The host left the room',
    settingsTitle: 'Settings', language: 'Interface language', arabic: 'العربية', english: 'English', sound: 'Sound effects', music: 'Background music', gameplay: 'Gameplay', appearance: 'Appearance', reset: 'Reset settings', cancel: 'Cancel', confirm: 'Confirm',
  },
} as const

export function useTranslation() {
  const language = useAppStore((state) => state.language)
  return { language, english: language === 'en', t: (key: keyof typeof strings.ar) => strings[language][key] }
}

const categoryEnglish: Record<string, string> = {
  'general-knowledge': 'General Knowledge', science: 'Science', technology: 'Technology', riddles: 'Riddles', intelligence: 'Logic & Intelligence', celebrities: 'Celebrities', cars: 'Cars', companies: 'Companies', currencies: 'Currencies', inventions: 'Inventions', logos: 'Logos', 'who-am-i-general': 'Who am I?', countries: 'Countries', capitals: 'World Capitals', flags: 'Flags', cities: 'Cities', 'tourist-attractions': 'Landmarks', rivers: 'Rivers', mountains: 'Mountains', egypt: 'Egypt', 'arab-world': 'Arab World', 'city-country': 'City & Country', 'currency-country': 'Currencies & Countries', 'egyptian-history': 'Egyptian History', 'pharaonic-civilization': 'Pharaonic Civilization', 'islamic-history': 'Islamic History', 'world-wars': 'World Wars', civilizations: 'Civilizations', 'historical-figures': 'Historical Figures', 'arabic-movies': 'Arabic Movies', 'foreign-movies': 'Foreign Movies', marvel: 'Marvel', dc: 'DC', 'harry-potter': 'Harry Potter', 'fast-furious': 'Fast & Furious', 'egyptian-series': 'Egyptian Series', 'arabic-series': 'Arabic Series', 'turkish-series': 'Turkish Series', 'korean-series': 'Korean Series', netflix: 'Netflix', actors: 'Actors', actresses: 'Actresses', 'who-is-character': 'Who is this character?', 'egyptian-posters': 'Egyptian Posters', football: 'Football', 'world-cup': 'World Cup', 'uefa-champions': 'UEFA Champions League', 'english-premier': 'English Premier League', 'la-liga': 'La Liga', 'serie-a': 'Serie A', bundesliga: 'Bundesliga', 'ligue-1': 'Ligue 1', 'egyptian-league': 'Egyptian League', 'saudi-league': 'Saudi League', 'national-teams': 'National Teams', clubs: 'Clubs', 'club-logos': 'Club Logos', stadiums: 'Stadiums', coaches: 'Coaches', referees: 'Referees', 'player-transfers': 'Transfers', records: 'Records', messi: 'Messi', ronaldo: 'Ronaldo', 'mohamed-salah': 'Mohamed Salah', basketball: 'Basketball', tennis: 'Tennis', 'formula-1': 'Formula 1', wwe: 'WWE', ufc: 'UFC', 'match-result': 'Match Results', 'player-career': 'Player Careers', 'who-am-i-sports': 'Who am I?', 'who-scored': 'Who Scored?', 'world-cup-26': 'World Cup 2026',
}
const sectionEnglish: Record<string, string> = { all: 'All', general: 'General', geography: 'Geography', history: 'History', movies: 'Movies', sports: 'Sports' }
const lifelineEnglish: Record<string, { label: string; description: string }> = {
  double: { label: 'Double points', description: 'Double this question\'s points' }, 'two-answers': { label: 'Four answers', description: 'Reveal up to four available answers' }, block: { label: 'Block opponent', description: 'Prevent the other team from answering' }, call: { label: 'Call a friend', description: 'Ask for help for 30 seconds' }, wheel: { label: 'Lucky wheel', description: 'Spin for a random reward' },
}
export function presentCategory(id: string, arabic: string, english: boolean) { return english ? categoryEnglish[id] ?? id : arabic }
export function presentSection(id: string, arabic: string, english: boolean) { return english ? sectionEnglish[id] ?? id : arabic }
export function presentLifeline(id: string, arabic: string, description: string, english: boolean) { return english ? lifelineEnglish[id] ?? { label: id, description: id } : { label: arabic, description } }
