import { useEffect } from 'react'
import { motion } from 'framer-motion'
import { useNavigate } from 'react-router-dom'
import { CategoryGrid } from '../components/create-game/CategoryGrid'
import { GameSetupForm } from '../components/create-game/GameSetupForm'
import { LifelineSelector } from '../components/create-game/LifelineSelector'
import { useGameBoardStore } from '../store/gameBoardStore'
import { useGameSetupStore } from '../store/gameSetupStore'
import { useTranslation } from '../i18n/translations'

export function CreateGame() {
  const navigate = useNavigate(); const { t, language } = useTranslation()
  const { gameName, team1Name, team2Name, team1Players, team2Players, team1CategoryIds, team2CategoryIds, team1LifelineIds, team2LifelineIds, activeTeam, setGameName, setTeam1Name, setTeam2Name, adjustTeam1Players, adjustTeam2Players, toggleCategory, getCategoryOwner, toggleLifeline, canStartGame, resetCategories } = useGameSetupStore()
  useEffect(() => { resetCategories() }, [resetCategories])
  const initializeBoard = useGameBoardStore((state) => state.initializeBoard)
  const handleStartGame = async () => { if (!canStartGame()) return; useGameBoardStore.setState({ isInitialized: false, team1Lifelines: [], team2Lifelines: [], activeQuestion: null, pendingDoublePoints: null, blockActive: null, callFriendActive: null, callFriendTimeLeft: 0 }); await initializeBoard(); navigate('/board') }
  const steps = [{ number: 1, label: t('stepsTeams'), icon: '♟' }, { number: 2, label: t('stepsCategories'), icon: '▦' }, { number: 3, label: t('stepsSettings'), icon: '⚙' }, { number: 4, label: t('stepsReview'), icon: '✓' }]
  return <div dir={language === 'ar' ? 'rtl' : 'ltr'} className="mx-auto w-full max-w-[1400px] space-y-4"><div className="glass-dark px-4 py-3.5 sm:px-6"><div className="mb-3 flex items-center justify-between"><div><p className="eyebrow">{t('arena')}</p><h1 className="font-display mt-0.5 text-lg font-extrabold text-cream sm:text-xl">{t('createTitle')}</h1></div><span className="hidden text-xs text-cream/55 sm:block sm:text-sm">{t('createDesc')}</span></div><motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.35, ease: 'easeOut' }} className="grid grid-cols-4 gap-2 sm:gap-4">{steps.map((step, index) => <motion.div key={step.number} initial={{ opacity: 0, y: 10, scale: 0.94 }} animate={{ opacity: 1, y: 0, scale: 1 }} transition={{ duration: 0.32, ease: 'easeOut', delay: index * 0.07 }} className="relative flex min-w-0 items-center gap-2"><div className={`relative z-10 flex h-8 w-8 shrink-0 items-center justify-center rounded-full border text-sm font-black transition sm:h-9 sm:w-9 ${step.number === 2 ? 'border-gold/60 bg-gold/15 text-gold-bright shadow-[0_0_18px_rgba(201,162,39,.25)]' : step.number < 2 ? 'border-white/25 bg-white/10 text-cream' : 'border-white/12 bg-white/5 text-cream/50'}`}>{step.icon}</div><span className={`hidden truncate text-xs font-bold sm:block ${step.number === 2 ? 'text-gold-bright' : 'text-cream/60'}`}>{step.number} · {step.label}</span>{index < steps.length - 1 && <span className="absolute start-9 end-[-.75rem] top-4 hidden h-px bg-gradient-to-r from-gold/40 to-white/10 sm:block" />}</motion.div>)}</motion.div></div><div className="grid min-w-0 items-start gap-4 lg:grid-cols-[minmax(300px,340px)_minmax(0,1fr)]"><GameSetupForm gameName={gameName} team1Name={team1Name} team2Name={team2Name} team1Players={team1Players} team2Players={team2Players} team1Count={team1CategoryIds.length} team2Count={team2CategoryIds.length} activeTeam={activeTeam} canStart={canStartGame()} onGameNameChange={setGameName} onTeam1NameChange={setTeam1Name} onTeam2NameChange={setTeam2Name} onTeam1PlayersDecrease={() => adjustTeam1Players(-1)} onTeam1PlayersIncrease={() => adjustTeam1Players(1)} onTeam2PlayersDecrease={() => adjustTeam2Players(-1)} onTeam2PlayersIncrease={() => adjustTeam2Players(1)} onStartGame={handleStartGame}><LifelineSelector teamId={1} teamName={team1Name || t('teamOne')} selectedIds={team1LifelineIds} onToggle={toggleLifeline} /><LifelineSelector teamId={2} teamName={team2Name || t('teamTwo')} selectedIds={team2LifelineIds} onToggle={toggleLifeline} /></GameSetupForm><CategoryGrid activeTeam={activeTeam} team1Count={team1CategoryIds.length} team2Count={team2CategoryIds.length} getCategoryOwner={getCategoryOwner} onToggleCategory={toggleCategory} /></div></div>
}
