import { motion } from 'framer-motion'
import { useState } from 'react'
import type { ReactNode } from 'react'
import { useAppStore } from '../store/appStore'
import { Settings as SettingsIcon, RefreshCcw } from 'lucide-react'

type RowProps = { icon: string; title: string; description: string; children: ReactNode }

type ToggleProps = { checked: boolean; onChange: (value: boolean) => void; label: string }

function Toggle({ checked, onChange, label }: ToggleProps) {
  return (
    <button type="button" role="switch" aria-checked={checked} aria-label={label} onClick={() => onChange(!checked)} className={`relative inline-flex h-7 w-12 shrink-0 items-center rounded-full border p-1 transition duration-200 ${checked ? 'border-navy-3 bg-navy-3' : 'border-border-strong bg-surface-raised'}`}>
      <span className={`h-5 w-5 rounded-full bg-white shadow-md transition-transform duration-200 ${checked ? 'translate-x-5' : 'translate-x-0'}`} />
    </button>
  )
}

function SettingRow({ icon, title, description, children }: RowProps) {
  return <div className="flex flex-col gap-4 rounded-2xl border border-border-soft bg-white/80 p-4 transition hover:border-border-strong sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-teal/10 text-lg text-teal" aria-hidden>{icon}</span><div><h3 className="font-black text-ink">{title}</h3><p className="mt-1 text-sm leading-relaxed text-muted">{description}</p></div></div><div className="shrink-0 self-end sm:self-auto">{children}</div></div>
}

function Section({ icon, title, description, children }: { icon: string; title: string; description: string; children: ReactNode }) {
  return <motion.section initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.25 }} className="glass-panel p-4 sm:p-5"><div className="mb-4 flex items-start gap-3 border-b border-border-soft pb-4"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-navy/10 text-xl text-navy" aria-hidden>{icon}</span><div><h2 className="text-lg font-black text-navy">{title}</h2><p className="mt-1 text-sm text-muted">{description}</p></div></div><div className="space-y-3">{children}</div></motion.section>
}

export function Settings() {
  const { language, direction, setLanguage, soundEnabled, setSoundEnabled, questionDuration, setQuestionDuration, enabledLifelines, toggleLifelineAvailability, theme, setTheme, animationsEnabled, setAnimationsEnabled, resetAppSettings } = useAppStore()
  const [confirmReset, setConfirmReset] = useState(false)
  const english = language === 'en'
  const reset = () => { resetAppSettings(); setConfirmReset(false) }

  return <div className="mx-auto max-w-5xl space-y-6" dir={direction}>
    <motion.header initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} className="relative overflow-hidden rounded-3xl border border-navy-3/30 bg-gradient-to-br from-navy via-navy-2 to-navy-3 p-6 text-white shadow-panel sm:p-8"><div className="pointer-events-none absolute -left-12 -top-16 h-40 w-40 rounded-full bg-gold/15 blur-2xl" /><div className="relative flex items-center justify-between gap-4"><div><p className="text-sm font-bold text-white/70">{english ? 'Customize your experience' : 'تخصيص التجربة'}</p><h1 className="mt-1 text-3xl font-black tracking-tight sm:text-4xl">{english ? 'Settings' : 'الإعدادات'}</h1><p className="mt-2 max-w-xl text-sm leading-relaxed text-white/80">{english ? 'Control supported interface and sound settings without changing the game experience.' : 'تحكم في إعدادات الواجهة والصوت التي تدعمها اللعبة، مع الحفاظ على تجربة اللعب كما هي.'}</p></div><div className="flex h-16 w-16 shrink-0 items-center justify-center rounded-2xl border border-white/15 bg-white/8" aria-hidden><SettingsIcon className="h-8 w-8 text-cream/60" /></div></div></motion.header>

    <div className="grid gap-5 lg:grid-cols-2">
      <Section icon="⚙️" title={english ? 'General' : 'الإعدادات العامة'} description={english ? 'Language and interface preferences.' : 'إعدادات اللغة وطريقة عرض الواجهة.'}><SettingRow icon="🌐" title={english ? 'Interface language' : 'لغة الواجهة'} description={english ? 'Change language and direction.' : 'تغيير اتجاه ولغة عناصر التطبيق.'}><div className="flex rounded-xl border border-border-soft bg-surface-raised p-1"><button type="button" onClick={() => setLanguage('ar')} className={`rounded-lg px-3 py-1.5 text-sm font-bold transition ${direction === 'rtl' ? 'bg-navy-3 text-white shadow-sm' : 'text-muted hover:text-ink'}`}>{english ? 'Arabic' : 'العربية'}</button><button type="button" onClick={() => setLanguage('en')} className={`rounded-lg px-3 py-1.5 text-sm font-bold transition ${direction === 'ltr' ? 'bg-navy-3 text-white shadow-sm' : 'text-muted hover:text-ink'}`}>English</button></div></SettingRow></Section>
      <Section icon="🔊" title={english ? 'Sound' : 'الصوت'} description={english ? 'Control available game sound effects.' : 'تحكم في المؤثرات الصوتية المتاحة أثناء اللعب.'}><SettingRow icon="🔊" title="المؤثرات الصوتية" description="أصوات اختيار الخانات والإجابة والمساعدات."><Toggle checked={soundEnabled} onChange={setSoundEnabled} label="تشغيل المؤثرات الصوتية" /></SettingRow></Section>
      <Section icon="🎮" title={english ? 'Gameplay' : 'إعدادات اللعب'} description={english ? 'New-game availability settings.' : 'إعدادات تطبق على المباريات الجديدة.'}><SettingRow icon="⏱️" title={english ? 'Question duration' : 'مدة السؤال'} description={english ? 'Applied to new questions.' : 'تطبق على الأسئلة الجديدة فقط.'}><select value={questionDuration} onChange={(event) => setQuestionDuration(Number(event.target.value) as typeof questionDuration)} className="rounded-xl border border-border-soft bg-surface-raised px-3 py-2 text-sm font-black text-navy outline-none transition focus:border-teal focus:ring-2 focus:ring-teal/20">{[15, 20, 30, 45, 60].map((duration) => <option key={duration} value={duration}>{duration} {english ? 'sec' : 'ثانية'}</option>)}</select></SettingRow><SettingRow icon="🛡️" title={english ? 'Available lifelines' : 'المساعدات المتاحة'} description={english ? 'Applied to new games only.' : 'تطبق على المباريات الجديدة فقط.'}><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{([['double', 'مضاعفة'], ['block', 'حظر'], ['call', 'اتصال'], ['two-answers', 'أربع إجابات'], ['wheel', 'العجلة']] as const).map(([id, label]) => <button key={id} type="button" onClick={() => toggleLifelineAvailability(id)} className={`rounded-lg border px-2 py-1 text-xs font-bold transition ${enabledLifelines.includes(id) ? 'border-green/40 bg-green/10 text-green' : 'border-border-soft bg-surface-raised text-muted'}`}>{enabledLifelines.includes(id) ? '✓ ' : ''}{english ? id : label}</button>)}</div></SettingRow></Section>
      <Section icon="🎨" title={english ? 'Appearance' : 'المظهر'} description={english ? 'Choose the active visual theme.' : 'اختر النمط البصري النشط.'}><SettingRow icon="🌙" title={english ? 'Theme' : 'النمط'} description={english ? 'Changes the application shell immediately.' : 'يغير غلاف التطبيق فورًا.'}><div className="flex gap-2"><button type="button" onClick={() => setTheme('premium')} className={`rounded-lg px-3 py-1.5 text-xs font-bold ${theme === 'premium' ? 'bg-navy text-white' : 'bg-surface-raised text-muted'}`}>Premium</button><button type="button" onClick={() => setTheme('light')} className={`rounded-lg px-3 py-1.5 text-xs font-bold ${theme === 'light' ? 'bg-gold text-ink' : 'bg-surface-raised text-muted'}`}>Light</button></div></SettingRow><SettingRow icon="✨" title={english ? 'Transitions' : 'الحركات الانتقالية'} description={english ? 'Controls optional page transitions.' : 'يتحكم في انتقالات الصفحات الاختيارية.'}><Toggle checked={animationsEnabled} onChange={setAnimationsEnabled} label={english ? 'Transitions' : 'الحركات الانتقالية'} /></SettingRow></Section>
    </div>

    <Section icon="ℹ️" title={english ? 'Game information' : 'معلومات اللعبة'} description={english ? 'Information about the current version.' : 'معلومات عن النسخة الحالية.'}><div className="grid gap-3 text-sm sm:grid-cols-3"><div className="rounded-2xl bg-surface-raised p-4"><span className="block text-muted">{english ? 'Version' : 'الإصدار'}</span><strong className="mt-1 block text-ink">QuizMaster 1.0</strong></div><div className="rounded-2xl bg-surface-raised p-4"><span className="block text-muted">{english ? 'Language' : 'اللغة'}</span><strong className="mt-1 block text-ink">{english ? 'English' : 'العربية'}</strong></div><div className="rounded-2xl bg-surface-raised p-4"><span className="block text-muted">{english ? 'Status' : 'الحالة'}</span><strong className="mt-1 block text-green">{english ? 'Ready to play' : 'جاهزة للعب'}</strong></div></div></Section>

    <div className="flex flex-col gap-3 border-t border-border-soft pt-5 sm:flex-row sm:items-center sm:justify-between" dir={direction}><div><h2 className="font-black text-ink">{english ? 'Reset settings' : 'إعادة الإعدادات الافتراضية'}</h2><p className="mt-1 text-sm text-muted">{english ? 'Restore app settings only; game data is kept.' : 'يعيد إعدادات التطبيق فقط، ولا يمسح المباريات أو الأسئلة.'}</p></div><button type="button" onClick={() => setConfirmReset(true)} className="btn btn-danger rounded-xl px-4 py-2.5 text-sm font-black">{english ? 'Reset settings' : 'إعادة الإعدادات'}</button></div>
    {confirmReset && <div className="fixed inset-0 z-[70] flex items-center justify-center bg-navy/60 p-4" role="dialog" aria-modal="true" dir={direction}><motion.div initial={{ opacity: 0, scale: 0.96 }} animate={{ opacity: 1, scale: 1 }} className="w-full max-w-md rounded-3xl border border-border-soft bg-white p-6 text-center shadow-raised"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-red/10 text-xl"><RefreshCcw className="h-6 w-6 text-red" /></div><h2 className="mt-4 text-xl font-black text-ink">إعادة الإعدادات؟</h2><p className="mt-2 text-sm leading-relaxed text-muted">سيتم إعادة إعدادات التطبيق فقط دون المساس ببيانات اللعبة.</p><div className="mt-6 flex justify-center gap-3"><button type="button" onClick={() => setConfirmReset(false)} className="btn btn-ghost rounded-xl px-4 py-2 text-sm font-black">إلغاء</button><button type="button" onClick={reset} className="btn btn-danger rounded-xl px-4 py-2 text-sm font-black">إعادة الضبط</button></div></motion.div></div>}
  </div>
}
