import { motion } from 'framer-motion'
import { useState } from 'react'
import type { ReactNode } from 'react'
import { useAppStore } from '../store/appStore'

type RowProps = { icon: string; title: string; description: string; children: ReactNode }

type ToggleProps = { checked: boolean; onChange: (value: boolean) => void; label: string }

function Toggle({ checked, onChange, label }: ToggleProps) {
  return (
    <button type="button" role="switch" aria-checked={checked} aria-label={label} onClick={() => onChange(!checked)} className={`relative inline-flex h-7 w-12 shrink-0 items-center rounded-full border p-1 transition duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-400/60 ${checked ? 'border-sky-500 bg-gradient-to-r from-sky-500 to-teal-500 shadow-[0_0_16px_rgba(14,165,233,0.28)]' : 'border-slate-300 bg-slate-200'}`}>
      <span className={`h-5 w-5 rounded-full bg-white shadow-md transition-transform duration-200 ${checked ? 'translate-x-5' : 'translate-x-0'}`} />
    </button>
  )
}

function SettingRow({ icon, title, description, children }: RowProps) {
  return <div className="flex flex-col gap-4 rounded-2xl border border-slate-200/80 bg-white/60 p-4 transition hover:border-sky-200 hover:bg-white/90 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-sky-50 text-lg shadow-inner ring-1 ring-sky-100" aria-hidden>{icon}</span><div><h3 className="font-bold text-slate-800">{title}</h3><p className="mt-1 text-sm leading-relaxed text-slate-500">{description}</p></div></div><div className="shrink-0 self-end sm:self-auto">{children}</div></div>
}

function Section({ icon, title, description, children }: { icon: string; title: string; description: string; children: ReactNode }) {
  return <motion.section initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.25 }} className="rounded-3xl border border-slate-200/80 bg-white/75 p-4 shadow-[0_14px_35px_rgba(15,118,110,0.07)] backdrop-blur-sm sm:p-5"><div className="mb-4 flex items-start gap-3 border-b border-slate-200/70 pb-4"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-sky-500 to-teal-500 text-xl text-white shadow-[0_8px_18px_rgba(14,165,233,0.22)]" aria-hidden>{icon}</span><div><h2 className="text-lg font-black text-slate-800">{title}</h2><p className="mt-1 text-sm text-slate-500">{description}</p></div></div><div className="space-y-3">{children}</div></motion.section>
}

export function Settings() {
  const { language, direction, setLanguage, soundEnabled, setSoundEnabled, questionDuration, setQuestionDuration, musicEnabled, musicVolume, setMusicEnabled, setMusicVolume, enabledLifelines, toggleLifelineAvailability, theme, setTheme, animationsEnabled, setAnimationsEnabled, resetAppSettings } = useAppStore()
  const [confirmReset, setConfirmReset] = useState(false)
  const english = language === 'en'
  const reset = () => { resetAppSettings(); setConfirmReset(false) }

  return <div className="mx-auto max-w-5xl space-y-6" dir={direction}>
    <motion.header initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} className="relative overflow-hidden rounded-3xl border border-sky-200/80 bg-gradient-to-br from-sky-600 via-sky-500 to-teal-500 p-6 text-white shadow-[0_18px_45px_rgba(14,165,233,0.2)] sm:p-8"><div className="pointer-events-none absolute -left-12 -top-16 h-40 w-40 rounded-full bg-white/15 blur-2xl" /><div className="relative flex items-center justify-between gap-4"><div><p className="text-sm font-bold text-white/75">{english ? 'Customize your experience' : 'تخصيص التجربة'}</p><h1 className="mt-1 text-3xl font-black tracking-tight sm:text-4xl">{english ? 'Settings' : 'الإعدادات'}</h1><p className="mt-2 max-w-xl text-sm leading-relaxed text-white/80">{english ? 'Control supported interface and sound settings without changing the game experience.' : 'تحكم في إعدادات الواجهة والصوت التي تدعمها اللعبة، مع الحفاظ على تجربة اللعب كما هي.'}</p></div><div className="flex h-16 w-16 shrink-0 items-center justify-center rounded-2xl border border-white/25 bg-white/15 text-3xl shadow-inner" aria-hidden>⚙️</div></div></motion.header>

    <div className="grid gap-5 lg:grid-cols-2">
      <Section icon="⚙️" title={english ? 'General' : 'الإعدادات العامة'} description={english ? 'Language and interface preferences.' : 'إعدادات اللغة وطريقة عرض الواجهة.'}><SettingRow icon="🌐" title={english ? 'Interface language' : 'لغة الواجهة'} description={english ? 'Change language and direction.' : 'تغيير اتجاه ولغة عناصر التطبيق.'}><div className="flex rounded-xl border border-slate-200 bg-slate-50 p-1"><button type="button" onClick={() => setLanguage('ar')} className={`rounded-lg px-3 py-1.5 text-sm font-bold transition ${direction === 'rtl' ? 'bg-sky-500 text-white shadow-sm' : 'text-slate-500 hover:text-slate-800'}`}>{english ? 'Arabic' : 'العربية'}</button><button type="button" onClick={() => setLanguage('en')} className={`rounded-lg px-3 py-1.5 text-sm font-bold transition ${direction === 'ltr' ? 'bg-sky-500 text-white shadow-sm' : 'text-slate-500 hover:text-slate-800'}`}>English</button></div></SettingRow></Section>
      <Section icon="🔊" title={english ? 'Sound' : 'الصوت'} description={english ? 'Control available game sound effects.' : 'تحكم في المؤثرات الصوتية المتاحة أثناء اللعب.'}><SettingRow icon="🔊" title="المؤثرات الصوتية" description="أصوات اختيار الخانات والإجابة والمساعدات."><Toggle checked={soundEnabled} onChange={setSoundEnabled} label="تشغيل المؤثرات الصوتية" /></SettingRow><SettingRow icon="🎵" title={english ? 'Background music' : 'الموسيقى الخلفية'} description={english ? 'Generated locally with no external audio files.' : 'نغمات محلية بسيطة بدون ملفات خارجية.'}><div className="flex items-center gap-3"><Toggle checked={musicEnabled} onChange={setMusicEnabled} label={english ? 'Background music' : 'الموسيقى الخلفية'} /><input aria-label={english ? 'Music volume' : 'مستوى صوت الموسيقى'} type="range" min="0" max="1" step="0.05" value={musicVolume} onChange={(event) => setMusicVolume(Number(event.target.value))} disabled={!musicEnabled} className="w-24 accent-sky-500 disabled:opacity-40" /></div></SettingRow></Section>
      <Section icon="🎮" title={english ? 'Gameplay' : 'إعدادات اللعب'} description={english ? 'New-game availability settings.' : 'إعدادات تطبق على المباريات الجديدة.'}><SettingRow icon="⏱️" title={english ? 'Question duration' : 'مدة السؤال'} description={english ? 'Applied to new questions.' : 'تطبق على الأسئلة الجديدة فقط.'}><select value={questionDuration} onChange={(event) => setQuestionDuration(Number(event.target.value) as typeof questionDuration)} className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm font-black text-slate-700 outline-none transition focus:border-sky-400 focus:ring-2 focus:ring-sky-100">{[15, 20, 30, 45, 60].map((duration) => <option key={duration} value={duration}>{duration} {english ? 'sec' : 'ثانية'}</option>)}</select></SettingRow><SettingRow icon="🛡️" title={english ? 'Available lifelines' : 'المساعدات المتاحة'} description={english ? 'Applied to new games only.' : 'تطبق على المباريات الجديدة فقط.'}><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{([['double', 'مضاعفة'], ['block', 'حظر'], ['call', 'اتصال'], ['two-answers', 'أربع إجابات'], ['wheel', 'العجلة']] as const).map(([id, label]) => <button key={id} type="button" onClick={() => toggleLifelineAvailability(id)} className={`rounded-lg border px-2 py-1 text-xs font-bold transition ${enabledLifelines.includes(id) ? 'border-emerald-300 bg-emerald-50 text-emerald-700' : 'border-slate-200 bg-slate-100 text-slate-400'}`}>{enabledLifelines.includes(id) ? '✓ ' : ''}{english ? id : label}</button>)}</div></SettingRow></Section>
      <Section icon="🎨" title={english ? 'Appearance' : 'المظهر'} description={english ? 'Choose the active visual theme.' : 'اختر النمط البصري النشط.'}><SettingRow icon="🌙" title={english ? 'Theme' : 'النمط'} description={english ? 'Changes the application shell immediately.' : 'يغير غلاف التطبيق فورًا.'}><div className="flex gap-2"><button type="button" onClick={() => setTheme('premium')} className={`rounded-lg px-3 py-1.5 text-xs font-bold ${theme === 'premium' ? 'bg-slate-800 text-white' : 'bg-slate-100 text-slate-500'}`}>🌙 Premium</button><button type="button" onClick={() => setTheme('light')} className={`rounded-lg px-3 py-1.5 text-xs font-bold ${theme === 'light' ? 'bg-amber-400 text-white' : 'bg-slate-100 text-slate-500'}`}>☀️ Light</button></div></SettingRow><SettingRow icon="✨" title={english ? 'Transitions' : 'الحركات الانتقالية'} description={english ? 'Controls optional page transitions.' : 'يتحكم في انتقالات الصفحات الاختيارية.'}><Toggle checked={animationsEnabled} onChange={setAnimationsEnabled} label={english ? 'Transitions' : 'الحركات الانتقالية'} /></SettingRow></Section>
    </div>

    <Section icon="ℹ️" title={english ? 'Game information' : 'معلومات اللعبة'} description={english ? 'Information about the current version.' : 'معلومات عن النسخة الحالية.'}><div className="grid gap-3 text-sm sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><span className="block text-slate-400">{english ? 'Version' : 'الإصدار'}</span><strong className="mt-1 block text-slate-700">QuizMaster 1.0</strong></div><div className="rounded-2xl bg-slate-50 p-4"><span className="block text-slate-400">{english ? 'Language' : 'اللغة'}</span><strong className="mt-1 block text-slate-700">{english ? 'English' : 'العربية'}</strong></div><div className="rounded-2xl bg-slate-50 p-4"><span className="block text-slate-400">{english ? 'Status' : 'الحالة'}</span><strong className="mt-1 block text-emerald-700">{english ? 'Ready to play' : 'جاهزة للعب'}</strong></div></div></Section>

    <div className="flex flex-col gap-3 border-t border-slate-200/80 pt-5 sm:flex-row sm:items-center sm:justify-between" dir={direction}><div><h2 className="font-bold text-slate-800">{english ? 'Reset settings' : 'إعادة الإعدادات الافتراضية'}</h2><p className="mt-1 text-sm text-slate-500">{english ? 'Restore app settings only; game data is kept.' : 'يعيد إعدادات التطبيق فقط، ولا يمسح المباريات أو الأسئلة.'}</p></div><button type="button" onClick={() => setConfirmReset(true)} className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-2.5 text-sm font-bold text-rose-700 transition hover:border-rose-300 hover:bg-rose-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-rose-300">{english ? 'Reset settings' : 'إعادة الإعدادات'}</button></div>
    {confirmReset && <div className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-900/35 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" dir={direction}><motion.div initial={{ opacity: 0, scale: 0.96 }} animate={{ opacity: 1, scale: 1 }} className="w-full max-w-md rounded-3xl border border-slate-200 bg-white p-6 text-center shadow-2xl"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-rose-50 text-xl">↺</div><h2 className="mt-4 text-xl font-black text-slate-800">إعادة الإعدادات؟</h2><p className="mt-2 text-sm leading-relaxed text-slate-500">سيتم إعادة إعدادات التطبيق فقط دون المساس ببيانات اللعبة.</p><div className="mt-6 flex justify-center gap-3"><button type="button" onClick={() => setConfirmReset(false)} className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-bold text-slate-600 transition hover:bg-slate-50">إلغاء</button><button type="button" onClick={reset} className="rounded-xl bg-rose-600 px-4 py-2 text-sm font-bold text-white transition hover:bg-rose-700">إعادة الضبط</button></div></motion.div></div>}
  </div>
}
