import { motion } from 'framer-motion'
import { defaultLifelines } from '../../data/lifelines'
import { LIFELINES_PER_TEAM, type TeamId } from '../../types/game'
import type { LifelineId } from '../../types/board'
import { cn } from '../../utils/cn'
import { useTranslation, presentLifeline } from '../../i18n/translations'
interface Props { teamId: TeamId; teamName: string; selectedIds: LifelineId[]; onToggle: (teamId: TeamId, id: LifelineId) => void }
const allLifelines = defaultLifelines()
export function LifelineSelector({ teamId, teamName, selectedIds, onToggle }: Props) { const { t, english } = useTranslation(); const full = selectedIds.length >= LIFELINES_PER_TEAM; return <div className="space-y-3"><div className="flex items-center justify-between"><h3 className="text-sm font-bold text-slate-200">{t('lifelines')} · {teamName}</h3><span className="rounded-full bg-white/10 px-2 py-0.5 text-[10px] font-bold text-slate-400">{selectedIds.length} / {LIFELINES_PER_TEAM}</span></div><div className="grid grid-cols-2 gap-2">{allLifelines.map((lifeline) => { const selected = selectedIds.includes(lifeline.id); const disabled = !selected && full; const copy = presentLifeline(lifeline.id, lifeline.label, lifeline.description, english); return <motion.button key={lifeline.id} type="button" whileTap={!disabled ? { scale: .97 } : undefined} onClick={() => onToggle(teamId, lifeline.id)} disabled={disabled} className={cn('flex items-center gap-2 rounded-xl border px-3 py-2.5 text-start transition', selected ? teamId === 1 ? 'border-cyan-300/50 bg-cyan-400/10' : 'border-rose-300/50 bg-rose-400/10' : disabled ? 'cursor-not-allowed border-white/5 bg-white/[.02] opacity-40' : 'border-white/10 bg-white/[.03] hover:border-cyan-300/30')}><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-white/10 text-sm">{lifeline.icon}</span><div className="min-w-0 flex-1"><p className="text-xs font-bold text-slate-200">{copy.label}</p><p className="truncate text-[10px] text-slate-500">{copy.description}</p></div>{selected && <span className="text-xs font-bold text-cyan-300">✓</span>}</motion.button> })}</div></div> }
